name: Automated CI checks

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Run linter (eslint)
        run: npm run lint
      - name: Run type check (typescript)
        run: npm run typecheck
      - name: Run tests (Jest)
        run: npm test
