name: Automated CI checks

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Run linter (eslint)
        run: npm run lint
      - name: Run type check (typescript)
        run: npm run typecheck
      - name: Run tests (Jest)
        run: npm test
